server:
  port: 8088

spring:
  application:
    #服务名称，client端用来享受服务
    name: cloudserver
  cloud:
    zookeeper:
      #ZK_ADDRESS
      connect-string: localhost:2181
      discovery:
        register: true
        #服务地址
        instance-host: 10.150.27.29
        #服务端口
        instance-port: 8081
        enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/